appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lIgMwk0W0mwukGBcP4h2Yy76PF6Uk55ZRzpwKxsdk14Ia0qZ+uY3YSNxBTjiNFltyR5rF3Rcy4QumkFCTM4kB0Cp6qqz8ez/Tm1wLqejW9A9Esdnzsm9d2SF0wcAS6NjgoWq1vfGltfLEtHFRxmBGK6Cc5A7/7KP+21Hh6wj+Y3KSMuhOsGxk9JgioYy2XirGFBQ51iwtDLTKVr/mhOyoga6FtmTcMtyrTxhQQvAWRGg9XH4sbR+38xppe1q7DXE9gjmGjaHLtnHtrnm5yqNOUDBwOk8EtgBBcXegV1aAbyKKZXNwtaDQQtkk3jRCD+ADooo/D8uMD8TMLvg2k5cyn91e1t9FujN22RWb/VyiH8MQrcJ5oYqBHNXL8ABEsXxr3+8wUGyisJwcuvsIxfM5+PZ/WgsfMXs6KCKZXuFigbtQnPb6pp7eeWuYJGdwzj4GLGZgofkBCtzYifQuMaXt26qfMl5lBlrxHLXNhkLfK3/67amRwqeWUOUKWn+3wUOMBt6Be9kjijpdSpzetJ2JWwL7XydJFrFSKUU+l0Iwb6DIesRuZf/5Nd08flwFnZZ5DpgRCIQ6s0xtIOVrqcpzZNXHsnQ1dIFjhGtDxm5miAC45Mbd/tzKKWLjUfkssKUVRjPmY/EBc0PDrzmhLkq/TP9gzIXQy9OEp2KxHWjI3E=}
