travis:
  secure:
    BINSTAR_TOKEN: DdWzwogl2eqbCD1x1bIXn0iRhJYvGkBqgePga53i7FCcDR5n0+E5aLhtm74eh1/t0VdbwnZpmjzpA6f0pEX/nRp2ZRQZ2JDoB3nPj9onEEEjj7qSnzi/q1rTZI3qECC2eut1TrH4rhYDWHoBgsdwWYJZudK1RIy0dX4dwGtaazMsOXp/5QR4PO+Hn2wQCkr9vIHlngsEFitzG68zfWeuKw+Wtk1Yypt6o4ijUCNgvdQyJvAs2p8O/Ipg+xVNHcLgtbaufYLHQhGfH5wlHrn8z/NtYviNXTFQ+x5M5PJ61NALExDqEKGu9tIgPqqY9SPp08XSSZpXEAez+DWQTFqgiOtCTNMerGQ0LkHjrdb21g2uv3nbfTWkiNY7vrFM04TZovq0AOlX9JeIL1YaSja645SJ6WIpkSo/WvXInQogFdvVdUH2mdnKhMokzNf6RlCd6IfpFQCr32n3ytVHshn8aaaroYmbb+1j4xtCX3rkU3xkM5lG6u9mktS4AQsjvFMjhMJCvQFmN30pmEV5nDl1iWueDBwsOIdHhyU2N02EwVbTQpyptD0QivbbdVhSRfrkd3r5on9XCRcm37iRDIbEYy/BDlfWxw6jh4MPGAQ0CXT/PGKlvxJGVyhqnXSaWZywSv6q633gOY7QAxggqYj4Vg0vtYNc0y7sSUIcHjQyLXI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
